package com.club09.baccarat;
import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.net.*;
import java.util.*;
public class MainActivity extends Activity {
 private LanServer server;private WebView web;private LinearLayout root;private EditText nickname,ip;private String name="게스트",activeHost;private TextView status;private boolean playing,starting;
 private final int green=Color.rgb(7,27,23),gold=Color.rgb(229,195,135);
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(green);getWindow().setNavigationBarColor(green);name=getPreferences(0).getString("name","게스트");home();}
 private int dp(int n){return (int)(getResources().getDisplayMetrics().density*n+.5f);}
 private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(8),0,dp(8));return t;}
 private Button button(String label,Runnable action){Button b=new Button(this);b.setText(label);b.setTextColor(green);b.setTextSize(16);GradientDrawable bg=new GradientDrawable();bg.setColor(gold);bg.setCornerRadius(dp(10));b.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(12),0,0);b.setLayoutParams(p);b.setOnClickListener(v->action.run());return b;}
 private EditText input(String hint,String value){EditText e=new EditText(this);e.setSingleLine();e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setHint(hint);e.setText(value);e.setTextSize(18);e.setPadding(dp(12),dp(12),dp(12),dp(12));return e;}
 private void frame(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(green);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});setContentView(root);root.requestApplyInsets();}
 private void home(){playing=false;getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);frame();ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(24),dp(20),dp(24),dp(24));scroll.addView(body);root.addView(scroll);body.addView(text("CLUB 09",32,gold));body.addView(text("폰끼리 즐기는 LAN 바카라",20,Color.WHITE));body.addView(text("시작 100만 칩 · 최소 베팅 1만 칩",15,Color.LTGRAY));body.addView(text("닉네임",15,Color.LTGRAY));nickname=input("닉네임",name);nickname.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(16)});body.addView(nickname);body.addView(button("혼자 + 봇",()->startHost(true)));body.addView(button("2인 방 만들기",()->startHost(false)));body.addView(text("친구 폰에 입장",20,gold));ip=input("친구 폰 주소 예: 192.168.0.12",getPreferences(0).getString("ip",""));ip.setInputType(android.text.InputType.TYPE_CLASS_PHONE);body.addView(ip);body.addView(button("친구 폰에 연결",this::join));status=text("같은 Wi-Fi에 연결하세요. 방을 연 폰은 게임 화면을 켜두세요.\n\n가상 칩 전용 · 구매·환전 없음",14,Color.LTGRAY);body.addView(status);}
 private void remember(){name=nickname.getText().toString().trim();if(name.isEmpty())name="게스트";getPreferences(0).edit().putString("name",name).apply();}
 private void startHost(boolean solo){if(starting)return;remember();starting=true;status.setText("방을 여는 중…");new Thread(()->{LanServer candidate=new LanServer(file->getAssets().open(file));try{candidate.start(!solo);String info=solo?"혼자 + 봇":"친구에게 알려줄 주소: "+addresses();runOnUiThread(()->{starting=false;if(isFinishing()||isDestroyed()){candidate.close();return;}if(server!=null)server.close();server=candidate;openGame("127.0.0.1",solo?"solo":"host",info);});}catch(Exception e){candidate.close();runOnUiThread(()->{starting=false;if(!isFinishing()&&!isDestroyed())status.setText("방을 열지 못했습니다: "+e.getMessage());});}},"baccarat-start").start();}
 private void join(){if(starting)return;remember();String host=ip.getText().toString().trim();if(!privateIPv4(host)){status.setText("친구 폰 화면의 IPv4 주소만 입력하세요. 예: 192.168.0.12");return;}getPreferences(0).edit().putString("ip",host).apply();openGame(host,"join","친구 폰: "+host);}
 static boolean privateIPv4(String s){String[] q=s.split("\\.",-1);if(q.length!=4)return false;int[] p=new int[4];try{for(int i=0;i<4;i++){if(!q[i].matches("[0-9]{1,3}"))return false;p[i]=Integer.parseInt(q[i]);if(p[i]>255)return false;}}catch(NumberFormatException e){return false;}return p[0]==10||p[0]==192&&p[1]==168||p[0]==172&&p[1]>=16&&p[1]<=31||p[0]==169&&p[1]==254;}
 private String addresses(){List<String> list=new ArrayList<>();try{for(NetworkInterface n:Collections.list(NetworkInterface.getNetworkInterfaces()))if(n.isUp()&&!n.isLoopback())for(InetAddress a:Collections.list(n.getInetAddresses()))if(a instanceof Inet4Address&&privateIPv4(a.getHostAddress()))list.add(a.getHostAddress());}catch(Exception ignored){}return list.isEmpty()?"Wi-Fi 연결을 확인하세요":android.text.TextUtils.join(" / ",list);}
 private void openGame(String host,String mode,String info){playing=true;activeHost=host;getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);frame();LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(10),0,dp(10),0);bar.setGravity(Gravity.CENTER_VERTICAL);TextView label=text(info,14,gold);label.setTextIsSelectable(true);bar.addView(label,new LinearLayout.LayoutParams(0,-2,1));Button exit=new Button(this);exit.setText("앱 홈");exit.setOnClickListener(v->askHome());bar.addView(exit);root.addView(bar);web=new WebView(this);web.setBackgroundColor(green);WebSettings cfg=web.getSettings();cfg.setJavaScriptEnabled(true);cfg.setDomStorageEnabled(true);cfg.setAllowFileAccess(false);cfg.setAllowContentAccess(false);cfg.setSupportMultipleWindows(false);web.setWebViewClient(new WebViewClient(){
 @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest req){Uri u=req.getUrl();return !("http".equals(u.getScheme())&&activeHost.equals(u.getHost())&&u.getPort()==8765);}
 @Override public void onReceivedError(WebView view,WebResourceRequest req,WebResourceError error){if(req.isForMainFrame())label.setText("연결 실패 · 주소와 같은 Wi-Fi인지 확인 후 앱 홈에서 재시도");}
 });root.addView(web,new LinearLayout.LayoutParams(-1,0,1));web.loadUrl("http://"+host+":8765/?mode="+mode+"&name="+Uri.encode(name));}
 private void askHome(){new AlertDialog.Builder(this).setTitle("게임에서 나갈까요?").setMessage(server!=null?"내 폰에서 연 방은 종료됩니다.":"현재 방에서 퇴장합니다.").setNegativeButton("계속하기",null).setPositiveButton("나가기",(d,w)->leave()).show();}
 private void leave(){playing=false;WebView old=web;if(old!=null){old.evaluateJavascript("if(typeof session!=='undefined'&&session){fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,op:'leave'}),keepalive:true}).catch(()=>{});sessionStorage.removeItem('club09');}",null);new Handler(Looper.getMainLooper()).postDelayed(()->{old.stopLoading();old.destroy();},350);web=null;}if(server!=null){server.close();server=null;}home();}
 @Override public void onBackPressed(){if(playing)askHome();else super.onBackPressed();}
 @Override protected void onDestroy(){if(web!=null){web.stopLoading();web.destroy();web=null;}if(server!=null){server.close();server=null;}super.onDestroy();}
}
